"""empty message

Revision ID: e92efa74f13d
Revises: 
Create Date: 2024-03-12 21:21:07.246327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92efa74f13d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('items', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_orders_email')
        batch_op.create_index(batch_op.f('ix_orders_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_email'))
        batch_op.create_index('ix_orders_email', ['email'], unique=1)
        batch_op.drop_column('items')
        batch_op.drop_column('total')

    # ### end Alembic commands ###
